//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.31 at 12:56:24 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://www.topografix.com/GPX/1/1",
        xmlns = {
                @XmlNs(namespaceURI = "http://www.topografix.com/GPX/1/1", prefix = "")},

        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.topografix.gpx._1._1;

import javax.xml.bind.annotation.XmlNs;