//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.31 at 01:08:10 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://www.garmin.com/xmlschemas/TrackPointExtension/v1",
        xmlns = {
                @XmlNs(namespaceURI = "http://www.garmin.com/xmlschemas/TrackPointExtension/v1", prefix = "gpxtpx")},
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.garmin.xmlschemas.trackpointextension.v1;

import javax.xml.bind.annotation.XmlNs;